#!/usr/bin/env bash
# Build a source tarball of the published tree.
#
# Usage: tools/make-source.sh [output-directory]
#
# The tarball contains exactly what is needed to configure, build, test and package the
# application — nothing else. The repository root is derived from this script's own
# location so the script works from any checkout.
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
VERSION=$(sed -n 's/^project(.*VERSION \([0-9.]*\).*/\1/p' "$REPO/CMakeLists.txt" | head -1)
NAME=fan-fold-${VERSION}
OUT=${1:-$REPO/dist}
STAGE=$(mktemp -d "${TMPDIR:-/tmp}/fanfold-src-XXXXXX")
trap 'rm -rf "$STAGE"' EXIT

DEST="$STAGE/$NAME"
mkdir -p "$DEST"
cd "$REPO"

# Top-level project files.
for f in CMakeLists.txt LICENSE NOTICE README.md AGENTS.md .gitignore; do
    [ -e "$f" ] && cp "$f" "$DEST/"
done

# Sources, tests, vendored editor and packaging.
cp -a src tests third_party packaging tools "$DEST/"

# README media, so the tarball renders as the repository does.
if [ -d docs/fan-fold/media ]; then
    mkdir -p "$DEST/docs/fan-fold"
    cp -a docs/fan-fold/media "$DEST/docs/fan-fold/"
fi

# Guard: the unreleased theme catalogue must never reach a published tarball. The check
# targets the generated data itself rather than its name, so prose that merely mentions
# the catalogue does not trip it. The pattern is split so this script does not match
# itself when the staged tree includes tools/.
BANNER='GENERATED by generate_catalog'
TOKENS='static const Token t_'
if grep -rl "${BANNER}_header" "$DEST" --exclude=make-source.sh 2>/dev/null | grep -q .; then
    echo "REFUSED: generated catalogue header present in source tree" >&2
    exit 1
fi
if grep -rl "${TOKENS}0\[\]" "$DEST" --exclude=make-source.sh 2>/dev/null | grep -q .; then
    echo "REFUSED: catalogue token table present in source tree" >&2
    exit 1
fi

mkdir -p "$OUT"
tar -czf "$OUT/$NAME.tar.gz" -C "$STAGE" "$NAME"
echo "built: $OUT/$NAME.tar.gz"
sha256sum "$OUT/$NAME.tar.gz"
tar -tzf "$OUT/$NAME.tar.gz" | wc -l | xargs echo "entries:"
